language: node_js
node_js:
  - "8.1.3"
install:
  - npm install
before_script:
  - npm install -g firebase-tools
script:
  - npm run build:firebase
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive